os: osx
language: swift
osx_image: xcode11.4
branches:
 only:
  - master

script:
 - xcodebuild -workspace Roasters.xcworkspace -scheme Roasters -destination 'platform=iOS Simulator,name=iPhone 8' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
